spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/keep_younger?useUnicode=true&characterEncoding=utf-8&useSSL=true&useTimezone=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  redis:
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.mao.entity
server:
  port: 9000